// Renders the site's raster brand assets from the app's brand sources
// (brand/*.svg, generated by `bun run icons` at the repository root):
//   site/public/apple-touch-icon.png  180px, full-bleed ink tile (iOS masks it)
//   site/public/favicon-32.png        for 404.html, which Vite doesn't process
//   site/public/og.png                1200x630 share image
// index.html itself references brand/*.svg directly, so only these need
// regenerating when the brand changes. From the repository root:
//   bun site/scripts/build-brand-assets.ts   # CHROME_PATH=... to pick a browser
import { chromium } from '@playwright/test'
import { copyFileSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const ROOT = resolve(import.meta.dir, '../..')
const OUT = resolve(ROOT, 'site/public')
const dataUrl = (path: string, type: string) => `data:${type};base64,${readFileSync(resolve(ROOT, path)).toString('base64')}`
const appIcon = dataUrl('brand/app-icon.svg', 'image/svg+xml')
const charis = dataUrl('node_modules/@fontsource/charis-sil/files/charis-sil-latin-400-normal.woff2', 'font/woff2')

const b = await chromium.launch(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : { channel: 'chrome' })
const page = await b.newPage()

async function shoot(html: string, width: number, height: number, file: string) {
  await page.setViewportSize({ width, height })
  await page.setContent(`<!doctype html><html><head><style>
    @font-face { font-family: 'Charis SIL'; src: url(${charis}) format('woff2'); }
    html, body { margin: 0; width: ${width}px; height: ${height}px; overflow: hidden; }
  </style></head><body>${html}</body></html>`)
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: resolve(OUT, file), omitBackground: false })
}

// The app icon's tile is the 824px squircle centred on its 1024px canvas;
// scale it so the tile fills the square and let the ink ground cover the
// corners and the shadow.
const s = 180 / 824
await shoot(`<div style="width:180px;height:180px;background:#111111;position:relative;overflow:hidden">
  <img src="${appIcon}" style="position:absolute;width:${1024 * s}px;height:${1024 * s}px;left:${-100 * s}px;top:${-100 * s}px"></div>`,
  180, 180, 'apple-touch-icon.png')

await shoot(`<div style="width:1200px;height:630px;display:flex;align-items:center;justify-content:center;gap:40px;
  background:radial-gradient(640px 640px at 380px 315px, rgba(28,25,23,.06), rgba(28,25,23,0)), #fbfaf8;color:#1c1917">
  <img src="${appIcon}" width="300" height="300">
  <div><div style="font-family:'Charis SIL',serif;font-size:96px;letter-spacing:-.03em;line-height:1.05">Peitho Studio</div>
  <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','Noto Sans',Helvetica,Arial,sans-serif;font-size:36px;color:#6b635d;margin-top:14px">A Markdown editor powered by Peitho</div></div></div>`,
  1200, 630, 'og.png')

copyFileSync(resolve(ROOT, 'src-tauri/icons/32x32.png'), resolve(OUT, 'favicon-32.png'))
await b.close()
console.log('wrote apple-touch-icon.png, og.png, favicon-32.png')
