import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vite'
import { barefoot } from '@barefootjs/vite'
import { CSRAdapter } from '@barefootjs/client/csr-adapter'

const HERE = dirname(fileURLToPath(import.meta.url))

// The landing site is a single static page: `index.html` is the Vite
// entry, and its `<script type="module">` loads `src/main.ts`, which mounts
// the DownloadPanel island (twice: the hero button and the Download list)
// into placeholders the static HTML already carries. Everything else is
// plain HTML, so the page reads fine before — or without — any JavaScript.
export default defineConfig({
  // index.html references the brand assets in ../brand directly (single
  // source of truth: they are generated by the app's `bun run icons`), so
  // the dev server may read the repository root.
  server: { fs: { allow: [resolve(HERE, '..')] } },
  build: {
    outDir: 'dist',
    target: 'esnext',
    // Named explicitly: the barefoot plugin adds its own component entries
    // to the rollup input, and without this the page itself (Vite's
    // implicit root `index.html` entry) drops out of the build.
    rollupOptions: {
      input: { index: resolve(HERE, 'index.html') },
    },
  },
  plugins: [
    barefoot({
      adapter: new CSRAdapter(),
      components: ['src/components'],
    }),
    // The barefoot plugin sets `appType: 'custom'`, which assumes a separate
    // backend serves the HTML, so `vite` alone answered "Cannot GET /". This
    // site has no backend: hand the dev server back its own index.html.
    // Declared after barefoot (which is `enforce: 'pre'`) so this wins.
    { name: 'site-serve-index-html', config: () => ({ appType: 'spa' }) },
  ],
})
