import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig, normalizePath } from 'vite'
import { barefoot } from '@barefootjs/vite'
import { CSRAdapter } from '@barefootjs/client/csr-adapter'
import { rewriteOutOfRootUrls } from './vite/outOfRootAssets'

const HERE = dirname(fileURLToPath(import.meta.url))

// The landing page mounts DownloadPanel and embeds a recording of the Studio UI.
export default defineConfig({
  // index.html references the brand assets in ../brand directly (single
  // source of truth: they are generated by the app's `bun run icons`), so
  // the dev server may read the repository root.
  server: { fs: { allow: [resolve(HERE, '..')] } },
  build: {
    outDir: 'dist',
    target: 'esnext',
    // Named explicitly: the barefoot plugin adds its own component entries
    // to the rollup input, and without this the page itself (Vite's
    // implicit root `index.html` entry) drops out of the build.
    rollupOptions: {
      input: { index: resolve(HERE, 'index.html') },
    },
  },
  plugins: [
    barefoot({
      adapter: new CSRAdapter(),
      components: ['src/components'],
    }),
    // The barefoot plugin sets `appType: 'custom'`, which assumes a separate
    // backend serves the HTML, so `vite` alone answered "Cannot GET /". This
    // site has no backend: hand the dev server back its own index.html.
    // Declared after barefoot (which is `enforce: 'pre'`) so this wins.
    { name: 'site-serve-index-html', config: () => ({ appType: 'spa' }) },
    // The dev server can't serve index.html's `../brand/*.svg` references
    // (the build resolves them fine) — see vite/outOfRootAssets.ts.
    {
      name: 'site-serve-out-of-root-assets',
      apply: 'serve',
      transformIndexHtml: {
        order: 'pre',
        handler: (html) => rewriteOutOfRootUrls(html, normalizePath(HERE)),
      },
    },
  ],
})
