export const meta = {
  name: 'implement-todo',
  description: "Implement peitho-studio todo/*.md plans end-to-end: independent PRs off main by default, restacked sequentially only where they'd actually conflict",
  phases: [
    { title: 'Implement', detail: 'plan → implement → test → PR → self-review → Pullfrog loop, per todo, in parallel off main' },
    { title: 'Stack', detail: "check every pair of branches for a real conflict; restack sequentially only the ones that would conflict — leave the rest as independent PRs" },
    { title: 'Notify', detail: 'post the review-request comment on each PR, exactly once, only once it is genuinely ready' },
  ],
}

if (!args?.todoPaths?.length) {
  throw new Error('args.todoPaths is required — pass one or more todo/*.md paths, e.g. { todoPaths: ["todo/action-click-feedback.md"] }')
}
const todoPaths = args.todoPaths

const PR_INFO_SCHEMA = {
  type: 'object',
  properties: {
    todoPath: { type: 'string' },
    branch: { type: 'string', description: 'The branch this PR is on, as it currently sits on the remote.' },
    prNumber: { type: 'number' },
    prUrl: { type: 'string' },
    reviewRequestDraft: {
      type: 'string',
      description: 'A ready-to-post PR comment body, starting with "@kfly8", with **修正内容** / **確認方法** / **期待される結果** sections. Composed, NOT posted. Must NOT include any "Generated by Claude" / signature / attribution line of its own — see the prompt\'s own note on why.',
    },
    openHumanItems: {
      type: 'string',
      description: 'One-line summary of whatever is still unchecked under 完了条件 の「人間の判断が必要な項目」for this todo (e.g. "実機確認"), or "" if none.',
    },
  },
  required: ['todoPath', 'branch', 'prNumber', 'prUrl', 'reviewRequestDraft', 'openHumanItems'],
}

function implementPrompt(todoPath, total) {
  return `peitho-studio(このリポジトリ)の改善タスク計画 \`${todoPath}\` を、
企画の理解からPRレビュー完了直前まで一貫して担当してください。
${total > 1 ? `\n今回は複数タスク(${total}件)の同時実行です。他のタスクは別のワーク\nツリーで並行して進んでいます。今の時点ではまだどのタスクとも\nスタックしません(スタックが必要かは、全タスクの実装が終わった後、\n別工程が実際のコンフリクトの有無を見て一括判断します)。あなたは\n\`main\`を起点にした自分専用のブランチだけを気にしてください。\n` : ''}
## 1. 実装
- \`${todoPath}\` を全文読む。CLAUDE.md と docs/architecture.md のレイヤー
  分離ルール(domain/state/ipc/dom/components、engine/peitho.rs/lib.rs)に
  従って実装する。
- 計画の「スコープ」の「やらないこと」には手を出さない。
- 「完了条件」の「人間の判断が必要な項目」(実機確認など)には手を出さず、
  未チェックのまま残す。
- BarefootJSコンポーネント(.tsx)を編集するとき、またはシグナルの依存関係
  やリアクティブな更新の挙動が疑わしいときは \`barefootjs\` skillを使う。
  IRTest(\`@barefootjs/test\`)やbf CLI(\`bf debug graph\`等)から得られる
  情報はデバッグに役立つ。

## 2. テスト
- 機能要件は Given-When-Then 形式で書き、非エンジニアがテストを読むだけで
  「何を保証しているか」分かるようにする。
- 非機能要件(性能・堅牢性・エラー時の挙動など該当するものがあれば)は
  別のテストとして書く。
- 新規/変更した純粋関数には spec(典型入力)+ adversarial(境界値・不正
  入力・空文字)の両方を用意する。
- \`bun test\` / \`bun run typecheck\`(Rust変更があれば \`cargo test\`)を
  実行し、グリーンであることを確認する。
- 自分で書いたテストが通ることは「そのテストの呼び出し順・前提が実際の
  本番経路(Tauri commandの実際の呼び出し元、peitho-coreへの実データ、
  実機WKWebViewでのレンダリング)でも成り立つ」ことを保証しない。修正が
  実際に通る本番のエントリポイント(呼び出し元のTauri command名/UIの
  どの操作から発火するか)を名指しし、順序・タイミング・キャッシュ・
  クロスファイル状態への依存がないか、そのエントリポイントの実コードに
  対してトレースする。トレースし切れない場合(実機WKWebView依存など)は
  ごまかさず、「完了条件」の「人間の判断が必要な項目」として明示的に
  残す(1節のルールと同じ)。

## 3. コミットとPR
- このリポジトリのコミット粒度ルール(意味単位でコミットを分ける)に従って
  コミットする。
- 常に \`main\` を起点にした自分専用のブランチで作業し、\`gh pr create\` で
  \`main\` 向けのPRを作成する。他のタスクとの依存関係やスタック化は
  一切気にしなくてよい(後工程が判断する)。

## 4. セルフレビュー
- \`code-review\` skill、続けて \`simplify\` skill を自分の変更に対して
  実行し、指摘があれば対応する。

## 5. Pullfrogレビュー対応
- PRを作成したら、Pullfrogによる自動レビュー(PR作成/pushをトリガーに
  非同期で走る)が実際に投稿されるまで待つ。指摘があれば対応してプッシュ
  し、Pullfrogが最新のpush後のheadに対して改めてレビューし、未解決の
  指摘がなくなるまで繰り返す。
- 「自分では対応し終えた/問題ないはず」という自己判断だけでは「レビュー
  が通った」と見なさない。あくまでPullfrogが最新headに対して実際に
  レビューし、未解決の指摘がないことを確認する。

## 6. 仕上げ
- \`${todoPath}\` のfrontmatterの \`status\` を \`wip\` に更新する(まだ
  kfly8の最終確認が残っているため \`done\` にはしない)。
- レビュアーの割り当ては行わない(GitHubはPR作成者自身をレビュアーに
  指定できない仕様上の制約があるため)。代わりに、次の形式でレビュー
  リクエストコメントの本文を**作成するだけ**にとどめ、実際には投稿し
  ないこと(投稿は後工程が、スタック化の要否を確定させた後にまとめて
  行う):
  - \`@kfly8\` から書き始める。
  - **修正内容**: 何を・なぜ変更したかを1〜2文で。
  - **確認方法**: レビュアーが自分の手で確認できる具体的な手順
    (実行可能なコマンド・再現手順そのもの。「diffを見て」ではなく、
    実際に叩ける \`bun test\` 等のコマンドや操作手順を書く)。
  - **期待される結果**: その手順を実行したときに何が見えれば正しいか
    (テスト結果・挙動・以前あった症状が消えていること等、レビュアーが
    「一致しているか」を判断できる具体性で)。
  - **このコメント本文に "Generated by Claude" のような署名・帰属表記を
    自分で付け足さないこと。** 帰属表記はコミットメッセージとPR本文
    (作成時に既に付与済み)にのみ付くべきもので、この状態報告コメントに
    重ねて付けると同じ趣旨の署名が二重に表示されてしまう
    (実例: piconic-ai/barefootjs#3011 のコメントで実際に重複した)。

## 7. 報告
最後に、構造化出力で todoPath・branch(実際に使ったブランチ名)・
prNumber・prUrl・reviewRequestDraft(6節で作成したコメント本文全文)・
openHumanItems(「完了条件」の「人間の判断が必要な項目」のうち未チェック
のまま残っているものの一言サマリ。なければ空文字)を返してください。`
}

function stackPrompt(prs) {
  const list = prs.map(pr => `- \`${pr.branch}\`(PR #${pr.prNumber}, ${pr.todoPath})`).join('\n')
  return `以下の ${prs.length} 件のPRは、それぞれ \`main\` を起点にした独立した
ブランチとして既に作成・push済みです:

${list}

これらを「そのまま独立PRのままにする」か「直列スタック(stacked PR)に
組み直す」かを、実際のコンフリクトの有無に基づいて判断し、必要なら
実行してください。\`gh-stack\` skillを使ってください。

## 1. コンフリクト判定
- \`git fetch origin\` の後、上記ブランチの全ペアについて
  \`git merge-tree --write-tree origin/<branch-a> origin/<branch-b>\`
  (作業ツリーには触れない)でコンフリクトの有無を機械的に確認する。
  推測や「たぶん同じファイルを触っていそうだから」で判断しないこと。

## 2. 判断
- **どのペアもコンフリクトしない場合**: 何もしない。全PRを独立PRの
  ままにする。入力で渡されたPR情報をそのまま返す。
- **1ペアでもコンフリクトする場合**: 全PRを1本の直列スタックに組み直す。
  - 順序は、コンフリクトが実際に起きるペアの組み合わせをもとに、
    後続のリベースで発生する衝突回数・衝突箇所が最小になるよう決める
    (完全に独立なタスクほど下位に、互いにコンフリクトするタスク同士は
    隣接させる、など)。1で得たペアごとの結果を根拠にすること。
  - \`gh stack link\`(既存の独立PR群を後付けでスタックにまとめる。
    ローカルの追跡状態に依存しないAPI駆動のコマンド)で決めた順序の
    スタックを作る。
  - \`gh stack rebase\` で実際にリベースし、コンフリクトが出たら
    (下位ブランチのコミット単位で)解消する。
  - リベース後、スタック最上部で \`bun run typecheck\` / \`bun test\` /
    \`npx playwright test\`(Rust変更を含むPRが1つでもあれば
    \`cargo test\` も)を実行し、グリーンであることを確認してから
    \`gh stack submit --auto\` でpushする。
  - リベースでheadのSHAが変わった各PRについては、Pullfrogがその
    新しいheadに対して改めてレビューし、未解決の指摘がなくなるまで
    待って対応する(5節と同じ規律 — リベース前のPullfrog承認は
    新しいheadには通用しない)。
  - 各PRの \`reviewRequestDraft\` のうち、スタック化によって内容が
    変わったもの(例: 「このPRは #<下位PR番号> の上に積まれています」
    という一言を足す必要があるもの)があれば書き直す。

## 3. 報告
最終的な各PRの状態(スタックしたかどうかに関わらず)を、入力と同じ形
(todoPath・branch・prNumber・prUrl・reviewRequestDraft・openHumanItems)
の配列で返してください。`
}

function notifyPrompt(pr) {
  return `PR #${pr.prNumber}(${pr.prUrl}、${pr.todoPath})について、レビュー
リクエストコメントを投稿してください。ただし、次の4条件を**すべて**
自分で確認できた場合のみ、一度だけ投稿すること。1つでも欠ける場合は
投稿せず、その理由を報告してください(投稿しないこと自体は失敗では
ない):
  (a) Pullfrogがこのブランチの**現在の**head(このメッセージを受け取った
      時点で \`gh pr view ${pr.prNumber}\` して分かる最新head)に対して
      レビュー済みで、未解決の指摘がない。
  (b) CIが通っている。
  (c) マージコンフリクトがない。
  (d) 自分自身で \`gh pr diff ${pr.prNumber}\` を読み直し、見落としが
      ないことを確認した。

条件を満たしたら、以下の本文をそのまま(必要なら直近の差分に合わせて
微修正した上で)\`gh pr comment ${pr.prNumber}\` で投稿してください。
**この本文に "Generated by Claude" のような署名・帰属表記を自分で
付け足さないこと**(コミット/PR本文に既に付いている帰属表記と重複する
ため):

---
${pr.reviewRequestDraft}
---

投稿できたか、できなかった場合はその理由を報告してください。`
}

phase('Implement')
const implemented = (await parallel(
  todoPaths.map(todoPath => () => agent(implementPrompt(todoPath, todoPaths.length), {
    label: `implement:${todoPath}`,
    phase: 'Implement',
    isolation: 'worktree',
    schema: PR_INFO_SCHEMA,
  }))
)).filter(Boolean)

if (implemented.length === 0) {
  log('No todo made it through the Implement phase — stopping before Stack/Notify.')
  return { prs: [] }
}

let finalPRs = implemented
if (implemented.length > 1) {
  phase('Stack')
  const stackResult = await agent(stackPrompt(implemented), {
    label: 'stack-decision',
    phase: 'Stack',
    isolation: 'worktree',
    schema: { type: 'object', properties: { prs: { type: 'array', items: PR_INFO_SCHEMA } }, required: ['prs'] },
  })
  finalPRs = stackResult?.prs?.length ? stackResult.prs : implemented
} else {
  log('Only one todo — skipping the Stack phase entirely.')
}

phase('Notify')
const notified = await parallel(
  finalPRs.map(pr => () => agent(notifyPrompt(pr), { label: `notify:#${pr.prNumber}`, phase: 'Notify' }))
)

return finalPRs.map((pr, i) => ({ ...pr, notifyReport: notified[i] }))
